#!/usr/bin/env bash
# 可直接粘贴项目环境变量。敏感值建议写入 env.local.sh。

# export LD_LIBRARY_PATH=/opt/kunlun/lib:${LD_LIBRARY_PATH:-}
# export <P800_DEVICE_ENV>=0,1,2,3

: "${MODEL_HOST:=127.0.0.1}"
: "${MODEL_PORT:=8000}"
: "${MODEL_BASE_URL:=http://${MODEL_HOST}:${MODEL_PORT}}"
: "${MODEL_STARTUP_TIMEOUT:=1200}"
: "${MODEL_CHECK_TIMEOUT:=300}"
: "${MODEL_VALIDATE_TIMEOUT:=1800}"
: "${MODEL_BENCHMARK_TIMEOUT:=3600}"
: "${MODEL_SHUTDOWN_TIMEOUT:=60}"
: "${MODEL_READY_INTERVAL:=2}"
: "${MODEL_READY_PROBE_TIMEOUT:=15}"

export MODEL_HOST MODEL_PORT MODEL_BASE_URL
export MODEL_STARTUP_TIMEOUT MODEL_CHECK_TIMEOUT
export MODEL_VALIDATE_TIMEOUT MODEL_BENCHMARK_TIMEOUT
export MODEL_SHUTDOWN_TIMEOUT MODEL_READY_INTERVAL MODEL_READY_PROBE_TIMEOUT
